name: API Consistency checks

on: [pull_request]

jobs:
  consistency-checks:
    runs-on: ubuntu-latest
    steps:
    ### Setup ############################################
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install Speakeasy CLI
      run: curl -fsSL https://raw.githubusercontent.com/speakeasy-api/speakeasy/main/install.sh | sh
    - name: Install Spectral
      run: npm install -g @stoplight/spectral-cli
    - name: Install Anthropic
      run: pip3 install anthropic
    - name: Install Optic
      run: npm install -g @useoptic/optic
      ### General purpose linters ############################################
    - name: Run Redocly CLI linting
      run: npx @redocly/cli lint openapi.yaml --config redocly.yaml
      continue-on-error: true
    - name: Run Spectral linting
      run: spectral lint openapi.yaml --ruleset spectral-ruleset.yaml
      continue-on-error: true
    - name: Run Vacuum linting
      run: npx @quobix/vacuum lint openapi.yaml --ruleset vacuum-ruleset.yaml --details
      continue-on-error: true
    - name: Run Optic Linting
      env:
        OPTIC_TOKEN: ${{ secrets.OPTIC_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: optic run openapi.yaml
      continue-on-error: true
    ### AI linting ############################################
#    - name: AI linting
#      env:
#        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
#      run: python3 ./my-ai-linter.py openapi.yaml ai-ruleset.txt
#      continue-on-error: true
    ### Target tool linters ############################################
    - name: Run Readme linting (Developer portal)
      run: npx rdme openapi:validate openapi.yaml
      continue-on-error: true
    - name: Run Speakeasy linting (SDK)
      run: speakeasy lint openapi --schema=openapi.yaml
      continue-on-error: true
#####################################################