name: Breaking change checks

on: [pull_request]

jobs:
  breaking-change-checks:
    runs-on: ubuntu-latest
    steps:
      ### Setup ############################################
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: pr-branch
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: base
      - name: Install Optic
        run: npm install -g @useoptic/optic
      - name: Install OpenAPI-Changes
        run: npm i -g @pb33f/openapi-changes
      - name: Install bump
        run: npm install -g bump-cli
      ### Breaking change checks ############################################
      - name: Tufin/oasdiff checks
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: './base/openapi.yaml'
          revision: './pr-branch/openapi_with_new_property.yaml'
          fail-on-diff: false
      - name: Optic checks
        run: optic diff ./base/openapi.yaml ./pr-branch/openapi_with_new_property.yaml --check
        continue-on-error: true
      - name: Optic checks 2
        run: optic diff ./base/openapi.yaml ./pr-branch/openapi_endpoint_deleted.yaml --check
        continue-on-error: true
      - name: Pb33f OpenAPI-Changes summary
        run: openapi-changes summary ./base/openapi.yaml ./pr-branch/openapi_with_new_property.yaml --no-logo
        continue-on-error: true
      - name: OpenAPI-Changes report
        run: openapi-changes report ./base/openapi.yaml ./pr-branch/openapi_with_new_property.yaml --no-logo
        continue-on-error: true
      - name: OpenAPI-Changes HTML report
        run: openapi-changes html-report ./base/openapi.yaml ./pr-branch/openapi_with_new_property.yaml --no-logo
        continue-on-error: true
      - name: Archive OpenAPI-Changes HTML report
        uses: actions/upload-artifact@v4
        with:
          name: diff-report
          path: |
            report.html
      - name: Bump.sh breaking change check
        run: bump diff ./base/openapi.yaml ./pr-branch/openapi_with_new_property.yaml
      ## Changelog generation ############################################
      - name : Oasdiff - Generate Changelog
        # For how to create a tenant key, see https://github.com/Tufin/oasdiff/blob/main/OASDIFF-SERVICE.md
        run:  curl -X POST -F base=@./base/openapi.yaml -F revision=@./pr-branch/openapi_endpoint_deleted.yaml  https://api.oasdiff.com/tenants/${{ secrets.OASDIFF_TENANT_KEY }}/changelog
      - name: Optic - Generate changelog
        run: | 
          cd base 
          optic history openapi.yaml

