name: Breaking change checks

on: [pull_request]

jobs:
  breaking-change-checks:
    runs-on: ubuntu-latest
    steps:
      ### Setup ############################################
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: pr-branch
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: base
      - name: Install Optic
        run: npm install -g @useoptic/optic
      - name: Install OpenAPI-Changes
        run: npm i -g @pb33f/openapi-changes
      ### Checks ############################################
      - name: Tufin/oasdiff checks
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: './base/openapi.yaml'
          revision: './pr-branch/openapi.yaml'
          fail-on-diff: false
      - name: Optic checks
        run: optic diff ./base/openapi.yaml ./pr-branch/openapi.yaml --check
        continue-on-error: true
      - name: Optic checks 2
        run: |
          cd pr-branch
          optic diff openapi.yaml --base main
        continue-on-error: true
