name: Code Generation Controls

on:
  pull_request:
  workflow_dispatch:

jobs:
  code-generation:
    runs-on: ubuntu-latest
    steps:
      ### Setup ############################################
      - name: Checkout PR branch
        uses: actions/checkout@v4
      - name: Install Fern
        run: npm install -g fern-api
      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli
      - name: Setup Kiota # Kiota from Micrsoft, is a command line tool for generating an API clients in C#, Java, Go, Python, TypeScript etc
        uses: microsoft/setup-kiota@v0.5.0
      ### Generating code ############################################
      - name: Generate clients with Fern
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          cd fern
          fern generate
      - name: Generate stub Spring server with OpenAPI Generator
        run: |
          openapi-generator-cli generate --input-spec openapi.yaml --generator-name spring --output openapi-generated-museum-service --additional-properties=library=spring-boot,apiPackage=com.museum.controller,modelPackage=com.museum.model,configPackage=com.museum.configuration,basePackage=com.museum,useTags=true
      - name: Generate Java API client with Kiota
        run: kiota generate --language java --namespace-name uk.co.ikenna.museum --openapi ./openapi_3.0.yaml  --output ./generated-kiota-museum
      - name: Archive generated code
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          path: |
            openapi-generated-museum-service
            fern-generated
            generated-kiota-museum
    




