name: Code Generation Controls

on: [pull_request]

jobs:
  conformance-tests:
    runs-on: ubuntu-latest
    steps:
      ### Setup ############################################
      - name: Checkout PR branch
        uses: actions/checkout@v4
      - name: Install Fern
        run: npm install -g fern-api
      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli
      ### Generating code ############################################
      - name: Generate clients with Fern
        run: |
          cd fern
          fern generate
      - name: Generate Java client with Speakeasy
        run: speakeasy generate sdk --lang=java --out=speakeasy-generated --schema=openapi.yaml
      - name: Generate stub Spring server with OpenAPI Generator
        run: |
          openapi-generator-cli generate --input-spec openapi.yaml --generator-name spring --output openapi-generated-museum-service --additional-properties=library=spring-boot,apiPackage=com.museum.controller,modelPackage=com.museum.model,configPackage=com.museum.configuration,basePackage=com.museum,useTags=true
      - name: Archive generated code
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          path: |
            openapi-generated-museum-service
            fern-generated
            speakeasy-generated




